import React from 'react';
import styles from './Sobre.module.css'

export default function Sobre() {
	return (
		<div className={styles.sobreDiv}>
			<h2>Sobre nós</h2>
			<p>Lorem ipsum sodales suspendisse scelerisque nisi himenaeos odio, ornare massa ut vehicula integer phasellus ligula rhoncus, integer interdum porttitor non viverra quisque nisi, nulla leo aenean nullam nunc iaculis. sociosqu suspendisse quis aptent vitae duis laoreet vel justo et turpis, viverra eros diam fusce orci aenean class ipsum curabitur, pulvinar commodo mattis auctor condimentum per hendrerit per lorem. risus pellentesque nibh commodo massa sapien malesuada nulla, fermentum est pellentesque curabitur ultricies adipiscing quisque, nullam ornare felis curabitur ornare rhoncus. eu donec porttitor pellentesque ultrices ut gravida quisque cubilia iaculis donec, blandit elit blandit magna habitant quis eros curabitur turpis, integer consequat luctus aliquam sagittis nam ac porttitor nibh. 

Ultricies nulla fames pharetra id lectus ipsum amet elementum dictumst mattis porta, id condimentum cursus habitant rhoncus sodales quam posuere justo gravida, vivamus ante sapien taciti ut sodales primis adipiscing dolor mi. ad et vestibulum nisi auctor aliquam scelerisque dictum, porttitor lacus in habitasse netus condimentum leo, placerat dictumst orci dui fames aenean. pharetra aliquam erat nullam et egestas eleifend, elementum lacinia habitant dictumst diam class quisque, aliquam accumsan platea habitant ligula. tristique mollis facilisis blandit aptent sagittis sem iaculis pulvinar morbi ut blandit mattis, morbi euismod tortor interdum nec feugiat morbi pulvinar lectus sapien urna consectetur, et torquent lacus libero vestibulum class orci at quisque dictum luctus. 

Consequat ullamcorper consectetur hendrerit in vestibulum maecenas vulputate suspendisse vehicula vulputate, cubilia fermentum pharetra viverra metus vel a fusce eget, ligula inceptos vitae etiam aliquam cubilia sem lobortis aliquet. praesent in lacinia sollicitudin felis sapien himenaeos per, odio inceptos neque a platea velit rhoncus, eget cursus varius a dapibus aliquam. felis inceptos lacinia commodo quis felis eu ultrices suscipit at fringilla varius pulvinar imperdiet, placerat consequat hac ullamcorper faucibus netus laoreet augue rhoncus id ullamcorper. est cursus dictum blandit diam risus cras aliquam donec commodo, inceptos eros nulla conubia ullamcorper ligula proin vestibulum ad, suspendisse torquent et curabitur iaculis interdum lorem viverra. 

Ad quam himenaeos quis molestie nostra maecenas at sodales leo aptent maecenas, commodo tempor conubia lobortis diam lobortis blandit nec integer primis class praesent, a imperdiet etiam sapien vulputate consectetur quisque at non et. nisl fusce euismod fames mollis ut fusce ullamcorper, morbi lorem commodo fringilla suspendisse bibendum lorem, sed elit aenean pharetra hendrerit congue. odio duis nunc enim orci vestibulum enim tempor non habitant metus, phasellus quis proin in velit phasellus neque malesuada morbi aptent, pulvinar laoreet netus elementum laoreet feugiat tellus feugiat pulvinar. tellus metus nisl quis leo quisque ornare taciti, curae potenti condimentum pulvinar diam cras pulvinar lorem, mauris nibh maecenas euismod integer ullamcorper. 

Enim semper varius sociosqu sodales est, gravida consectetur sem vestibulum ultricies, purus et lacinia urna. aptent sociosqu eget etiam eget orci lobortis torquent sollicitudin, torquent per class sit accumsan aenean quisque per, luctus praesent augue nisi litora eget pretium. donec class congue mollis aliquet etiam sed, consectetur sed a interdum orci vitae lectus, etiam inceptos habitasse etiam porta. auctor cursus consequat class primis tristique consequat, porta fringilla nibh id imperdiet, aliquam ipsum nullam eros netus. </p>
		</div>
	);
}